name: stein
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - black=19.10b0
  - click=8.0.3
  - gpytorch=1.5.0
  - gym=0.18.0
  - ipykernel=5.5.5
  - ipython=7.27.0
  - jedi=0.18.0
  - jinja2=3.0.1
  - jupyter_client=7.0.1
  - jupyter_core=4.8.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - matplotlib-inline=0.1.2
  - moviepy=1.0.1
  - mypy_extensions=0.4.3
  - ninja=1.10.2
  - numexpr=2.7.3
  - numpy=1.21.2
  - pandas=1.3.4
  - pillow=8.4.0
  - pip=21.2.4
  - proglog=0.1.9
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycodestyle=2.7.0
  - pycparser=2.20
  - pyflakes=2.3.1
  - pyglet=1.5.16
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.6
  - python-dateutil=2.8.2
  - pytorch=1.9.0
  - pytz=2021.3
  - pyyaml=5.4.1
  - pyzmq=22.2.1
  - requests=2.26.0
  - scipy=1.7.1
  - seaborn=0.11.1
  - tqdm=4.61.2
  - typing_extensions=3.10.0.2
  - yaml=0.2.5
  - zeromq=4.3.4
