name: sigsvgd
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - black
  - gpytorch=1.5.0
  - gym
  - matplotlib
  - moviepy=1.0.1
  - python=3.9.6
  - pytorch=1.9.0
  - pyyaml
  - seaborn
  - tqdm=4.61.2
  - pybullet
  - plotly
  - altair
  - pip
  - pip:
      - signatory==1.2.6.1.9.0
      - cython
      - git+https://github.com/crispitagorico/sigkernel.git
      - git+https://github.com/patrick-kidger/torchcubicspline.git
