name: stein
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - black=19.10b0
  - gpytorch=1.5.0
  - gym=0.18.0
  - matplotlib=3.3.4
  - moviepy=1.0.1
  - python=3.9.6
  - pytorch=1.9.0
  - pyyaml=5.4.1
  - seaborn=0.11.1
  - tqdm=4.61.2
  - pip:
    - signatory==1.2.6.1.9.0
